### ISSUE TITLE
numbers in cell_type name are non-obvious

### ISSUE THREAD

**Issue by SchulzLab** [IHEC/epimap-metadata-harmonization#10]
There are several entries that are referred to as :	
immature lymphoid progenitor 2 from peripheral blood(4 rows)
immature lymphoid progenitor 3 from peripheral blood(4 rows)

These entries (e.g. IHECRE00002778.1, IHECRE00002784.1) have the same entries  in the column phenotype and markers, but come from different donors. I could not detect the naming principle that was applied, to refer to those entries with different numbers as part of their name. Likely, these should all have the same cell_type entry.

**Comment by daniel-rico** [comment]
I think each number simply refers to a different donor. We can simply remove the number.

**Comment by SchulzLab** [comment]
This was solved
