### ISSUE TITLE
ambiguous naming of b cells

### ISSUE THREAD

**Issue by SchulzLab** [IHEC/epimap-metadata-harmonization#13]
There are a lot of terms for b cells that seem to refer to the same cell. All b lymphocytes are CD19 positive cells.
<img width="679" alt="Bildschirmfoto 2021-06-14 um 15 00 55" src="https://user-images.githubusercontent.com/6179648/121896350-7d049800-cd21-11eb-80f0-4f3fb97d1542.png">

A similar issues exists for t cells

**Comment by SchulzLab** [comment]
The different names are corresponding to cell type names in the cell type ontology ID, however what we observed is that for some entries the same cell type( e.g. naive b cell0 was given but the marker column was empty or had changed markers. We did not impute markers here as we were not sure whether one could do this without making a mistake

**Comment by mlist** [comment]
We decided not to add markers where we are not sure. We fixed the b cell peripheral blood entry.
