### ISSUE TITLE
Tissue Type: "germinal matrix" ->? "future brain"

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#18]
Not in Uberon. From wikipedia: In anatomy, the germinal matrix is a highly cellular and highly vascularized region in the brain from which cells migrate out during brain development. The germinal matrix is the source of both neurons and glial cells and is most active between 8 and 28 weeks gestation.

**Comment by SchulzLab** [comment]
has been removed already

**Comment by quirinmanz** [comment]
renamed to "germinal neuroepithelium" https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0004022
