### ISSUE TITLE
Tissue Type: "large intestine-colon-rectosigmoid" ->? "sigmoid colon" or "rectum"

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#19]
Not in Uberon, though "sigmoid colon" and "rectum" are.
From wikipedia: The sigmoid colon is the part of the large intestine after the descending colon and before the rectum.
From wiley online ibrary: The rectosigmoid region denotes the last part of the sigmoid colon and the beginning of the rectum.

**Comment by SchulzLab** [comment]
not there anymore

**Comment by quirinmanz** [comment]
renamed to "sigmoid colon"
