### ISSUE TITLE
Tissue Type: "lung fibroblast" -> "lung"

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#20]
Fibroblast is a cell type, and should be moved to cell_type column.

**Comment by SchulzLab** [comment]
as this is a cell line (IMR-90) it should not have an entry in tissue type

**Comment by rnakato** [comment]
It is okay to change it to “lung” and set the cell_type column to “Fibroblast.”
(Naoto Kubota)
