### ISSUE TITLE
"superior vena cava endothelial cells" and "great saphenous vein endothelial cell": use CL "vein endothelial cell"?

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#23]
No CL is available for "superior vena cava endothelial cells" and "great saphenous vein endothelial cell, but "vein endothelial cell" is available 
example ids: "IHECRE00004757.1", "IHECRE00003772.1", "IHECRE00003770.1", "IHECRE00003782.1"

**Comment by rnakato** [comment]
Same with #24, we would like to keep the information of "superior vena cava" and "great saphenous vein" somewhere if possible. Could we use another column?
(Ryuichiro Nakato)

**Comment by SchulzLab** [comment]
We have moved the superior vena cava or great saphenous vein pat to the origin_sample column and changed the cell type name to the term vein endothelial cell (as matching to the oberon term)
