### ISSUE TITLE
"renal artery endothelial cells": use CL "arcuate artery endothelial cell"?

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#25]
No CL is available for "renal artery endothelial cells", but "arcuate artery endothelial cell" is available
From Wikpedia: "The arcuate arteries of the kidney, also known as arciform arteries, are vessels of the renal circulation. They are located at the border of the renal cortex and renal medulla."
example id: "IHECRE00004762.1"

**Comment by rnakato** [comment]
I asked Dr. Wada and confirmed that it is okay to change "renal artery endothelial cells" to "arcuate artery endothelial cells."
(Ryuichiro Nakato)

**Comment by mlist** [comment]
fixed
