### ISSUE TITLE
"cytotrophoblast": use CL "trophoblast cell" or "mononuclear cytotrophoblast cell"

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#26]
CL for variations of cytotrophoblast such as "cd49f_positive_cytotrophoblast", "cytotrophoblast cell" and "hla-g_positive_extravillous_cytotrophoblast" is not available, but "trophoblast cell" and "mononuclear cytotrophoblast cell" are.
example ids: "IHECRE00003716.2", "IHECRE00004591.1", "IHECRE00004721.1"

**Comment by rnakato** [comment]
It is okay to change all to “trophoblast cell.”
(Naoto Kubota)

**Comment by mlist** [comment]
done.
