### ISSUE TITLE
Markers column: link to protocol extraction

### ISSUE THREAD

**Issue by GFrosi** [IHEC/epimap-metadata-harmonization#3]
43 EpiRR related to Blueprint (ex: IHECRE00000071) had a link in the “marker” column that was erased. However, the corresponding protocols page 
(https://www.blueprint-epigenome.eu/index.cfm?p=7BF8A4B6-F4FE-861A-2AD57A08D63D0B58) is referring to “CD4 naive cells” so “CD4+” and perhaps “CD45RO+” also mentioned in the protocol could be added as “markers”

**Comment by daniel-rico** [comment]
IHECRE00000071 is actually an anti-inflammatory macrophage (M2): the protocol from the three type of macrophages (M0, M1 and M2) is here: https://www.blueprint-epigenome.eu/UserFiles/File/Protocols/UCAM_BluePrint_Macrophage.pdf
@GFrosi , could you give the 43 EpiRR IDs to check all of them please? We can find the right markers and put them (instead of the link)

**Comment by GFrosi** [comment]
Hi @daniel-rico ,

Thanks for your reply. Here are the 43 EpiRR IDs. 
If you need something else, please just let me know. 

IHECRE00000008.3
IHECRE00000013.3
IHECRE00000016.3
IHECRE00000019.3
IHECRE00000039.3
IHECRE00000043.3
IHECRE00000045.3
IHECRE00000055.3
IHECRE00000059.3
IHECRE00000060.3
IHECRE00000071.3
IHECRE00000079.3
IHECRE00000082.3
IHECRE00000084.3
IHECRE00000091.3
IHECRE00000099.3
IHECRE00000113.3
IHECRE00000121.3
IHECRE00000126.3
IHECRE00000129.3
IHECRE00000150.3
IHECRE00000151.3
IHECRE00000154.3
IHECRE00000158.3
IHECRE00000161.3
IHECRE00000174.3
IHECRE00000177.3
IHECRE00000184.3
IHECRE00000195.3
IHECRE00000255.2
IHECRE00000269.2
IHECRE00000303.2
IHECRE00000312.2
IHECRE00000318.2
IHECRE00001289.1
IHECRE00001293.1
IHECRE00001299.1
IHECRE00001384.1
IHECRE00001391.1
IHECRE00001398.1
IHECRE00001510.1
IHECRE00001555.1
IHECRE00001558.1

**Comment by daniel-rico** [comment]
Fantastic, thanks a lot!

Juliana will review them.

Cheers,
Daniel

Pronouns: he/him

**Comment by juearcilaga** [comment]
**Neutrophils**
CD16+

**Monocyte derived Macrophage**
CCR7, CD25, CD14, CD40 
CD206, CD36, CD45

**Monocytes**
CD14, CD42b, CD64, CD45

**Cord Blood Progenitor Populations**
Hematopoietic Stem Cell (HSC)
Multipotent Progenitor (MPP)
Common Lymphoid Progenitor (CLP)
Common Myeloid Progenitor (CMP)
Megakaryocyte-Erythroid Progenitor (MEP)
Granulocyte-Macrophage Progenitor (GMP)

- HSC: Lin-CD34+CD38-CD90+CD45RA-
- MPP: Lin-CD34+CD38-CD90-CD45RA-
- CLP: Lin-CD34+CD38+CD10+CD45RA+
- CMP: Lin-CD34+CD38+IL-3RalowCD45RA-
- MEP: Lin-CD34+CD38+IL-3Ra-CD45RA-
- GMP: Lin-CD34+CD38+IL-3Ra+CD45RA+

**naive CD4**
CD4, CD45RA

**Comment by GFrosi** [comment]
Thanks Juliana, 

however our "mission" is only to report the markers used or validated for each of these EpiRR (not the ones that are expected); could you complete the "marker" column of the following table when appropriate? If you are not sure we'll simply keep a blank (as most of the samples anyway).

Thanks a lot again.

EpiRR | biomaterial_type | tissue_type | cell_type| markers
IHECRE00000008.3 | primary cell culture | venous blood | macrophage |
IHECRE00000013.3 | primary cell culture | venous blood | alternatively activated macrophage |
IHECRE00000016.3 | primary cell culture | venous blood | macrophage |
IHECRE00000019.3 | primary cell culture | cord blood | inflammatory macrophage |
IHECRE00000039.3 | primary cell culture | venous blood | alternatively activated macrophage |
IHECRE00000043.3 | primary cell culture | venous blood | inflammatory macrophage |
IHECRE00000045.3 | primary cell culture | cord blood | endothelial cell of umbilical vein (resting) |
IHECRE00000055.3 | primary cell culture | cord blood | alternatively activated macrophage |
IHECRE00000059.3 | primary cell culture | venous blood | alternatively activated macrophage |
IHECRE00000060.3 | primary cell culture | cord blood | macrophage |
IHECRE00000071.3 | primary cell culture | venous blood | alternatively activated macrophage |
IHECRE00000079.3 | primary cell | cord blood | megakaryocyte-erythroid progenitor cell |
IHECRE00000082.3 | primary cell culture | venous blood | macrophage |
IHECRE00000084.3 | primary cell culture | venous blood | macrophage |
IHECRE00000091.3 | primary cell | cord blood | megakaryocyte-erythroid progenitor cell |
IHECRE00000099.3 | primary cell culture | cord blood | endothelial cell of umbilical vein (resting) |
IHECRE00000113.3 | primary cell culture | venous blood | inflammatory macrophage |
IHECRE00000121.3 | primary cell culture | cord blood | macrophage |
IHECRE00000126.3 | primary cell culture | cord blood | endothelial cell of umbilical vein (proliferating) |
IHECRE00000129.3 | primary cell culture | venous blood | alternatively activated macrophage |
IHECRE00000150.3 | primary cell | cord blood | megakaryocyte-erythroid progenitor cell |
IHECRE00000151.3 | primary cell culture | cord blood | macrophage |
IHECRE00000154.3 | primary cell | cord blood | megakaryocyte-erythroid progenitor cell |
IHECRE00000158.3 | primary cell culture | cord blood | conventional dendritic cell |
IHECRE00000161.3 | primary cell culture | venous blood | inflammatory macrophage |
IHECRE00000174.3 | primary cell culture | venous blood | inflammatory macrophage |
IHECRE00000177.3 | primary cell culture | venous blood | macrophage |
IHECRE00000184.3 | primary cell culture | cord blood | endothelial cell of umbilical vein (proliferating) |
IHECRE00000195.3 | primary cell culture | cord blood | inflammatory macrophage |
IHECRE00000255.2 | primary cell culture | cord blood | conventional dendritic cell |
IHECRE00000269.2 | primary cell culture | cord blood | alternatively activated macrophage |
IHECRE00000303.2 | primary cell | venous blood | adult endothelial progenitor cell |
IHECRE00000312.2 | primary cell culture | venous blood | alternatively activated macrophage |
IHECRE00000318.2 | primary cell culture | venous blood | inflammatory macrophage |
IHECRE00001289.1 | primary cell culture | cord blood | inflammatory macrophage |
IHECRE00001293.1 | primary cell culture | venous blood | inflammatory macrophage |
IHECRE00001299.1 | primary cell culture | venous blood | alternatively activated macrophage |
IHECRE00001384.1 | primary cell culture | cord blood | alternatively activated macrophage |
IHECRE00001391.1 | primary cell culture | venous blood | alternatively activated macrophage |
IHECRE00001398.1 | primary cell culture | venous blood | macrophage |
IHECRE00001510.1 | primary cell | venous blood | adult endothelial progenitor cell |
IHECRE00001555.1 | primary cell | venous blood | adult endothelial progenitor cell |
IHECRE00001558.1 | primary cell culture | cord blood | conventional dendritic cell |

**Comment by juearcilaga** [comment]
IHECRE00000303.2 | primary cell | venous blood | adult endothelial progenitor cell |  
IHECRE00001510.1 | primary cell | venous blood | adult endothelial progenitor   cell |  
IHECRE00001555.1 | primary cell | venous blood | adult endothelial progenitor   cell |  
IHECRE00000013.3 | primary cell culture | venous blood | alternatively activated   macrophage | CCR7,   CD25, CD14, CD40,CD206, CD36, CD45
IHECRE00000039.3 | primary cell culture | venous blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD46
IHECRE00000055.3 | primary cell culture | cord blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD47
IHECRE00000059.3 | primary cell culture | venous blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD48
IHECRE00000071.3 | primary cell culture | venous blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD49
IHECRE00000129.3 | primary cell culture | venous blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD50
IHECRE00000269.2 | primary cell culture | cord blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD51
IHECRE00000312.2 | primary cell culture | venous blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD52
IHECRE00001299.1 | primary cell culture | venous blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD53
IHECRE00001384.1 | primary cell culture | cord blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD54
IHECRE00001391.1 | primary cell culture | venous blood | alternatively activated   macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD55
IHECRE00000158.3 | primary cell culture | cord blood | conventional dendritic cell |  
IHECRE00000255.2 | primary cell culture | cord blood | conventional dendritic cell |  
IHECRE00001558.1 | primary cell culture | cord blood | conventional dendritic cell |  
IHECRE00000126.3 | primary cell culture | cord blood | endothelial cell of umbilical vein   (proliferating)
IHECRE00000184.3 | primary cell culture | cord blood | endothelial cell of umbilical vein   (proliferating)
IHECRE00000045.3 | primary cell culture | cord blood | endothelial cell of umbilical vein   (resting) |  
IHECRE00000099.3 | primary cell culture | cord blood | endothelial cell of umbilical vein   (resting) |  
IHECRE00000019.3 | primary cell culture | cord blood | inflammatory macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD55
IHECRE00000043.3 | primary cell culture | venous blood | inflammatory macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD56
IHECRE00000113.3 | primary cell culture | venous blood | inflammatory macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD57
IHECRE00000161.3 | primary cell culture | venous blood | inflammatory macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD58
IHECRE00000174.3 | primary cell culture | venous blood | inflammatory macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD59
IHECRE00000195.3 | primary cell culture | cord blood | inflammatory macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD60
IHECRE00000318.2 | primary cell culture | venous blood | inflammatory macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD61
IHECRE00001289.1 | primary cell culture | cord blood | inflammatory macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD62
IHECRE00001293.1 | primary cell culture | venous blood | inflammatory macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD63
HECRE00000008.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD63
IHECRE00000016.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD64
IHECRE00000060.3 | primary cell culture | cord blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD65
IHECRE00000082.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD66
IHECRE00000084.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD67
IHECRE00000121.3 | primary cell culture | cord blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD68
IHECRE00000151.3 | primary cell culture | cord blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD69
IHECRE00000177.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD70
IHECRE00001398.1 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, CD71
IHECRE00000079.3 | primary cell | cord blood | megakaryocyte-erythroid progenitor   cell | Lin-CD34+CD38+IL-3Ra-CD45RA-
IHECRE00000091.3 | primary cell | cord blood | megakaryocyte-erythroid progenitor   cell | Lin-CD34+CD38+IL-3Ra-CD45RA-
IHECRE00000150.3 | primary cell | cord blood | megakaryocyte-erythroid progenitor   cell | Lin-CD34+CD38+IL-3Ra-CD45RA-
IHECRE00000154.3 | primary cell | cord blood | megakaryocyte-erythroid progenitor   cell | Lin-CD34+CD38+IL-3Ra-CD45RA-


The information about the markers comes from the documentation of the protocols: Blueprint Epigenome - Protocols (blueprint-epigenome.eu). Macrophages are derived from monocytes, they used the marker before inducing their differentiation in M0, M1 and M2 (https://www.blueprint-epigenome.eu/UserFiles/File/Protocols/UCAM_BluePrint_Macrophage.pdf).

I couldn't find information about the markers of endothelial cells and dendritic cells

**Comment by juearcilaga** [comment]
Hello Juliana,

Do you think we can assume the positive symbol for the Markers that you described on git? Or should we just keep the markers with this description? (e.g Lin-CD34+CD38+IL-3Ra-CD45RA-

Thanks a lot for your help!

Gabriella Frosi

**Comment by juearcilaga** [comment]
Hi Gabriella,

In the columns where the markers do not have a symbol, we can assume positive (According to what Daniel and I interpret from the Blueprint's protocol). In the columns where there are negative symbols, I spoke to Daniel, and we think it is important to keep that information. This example  (e.g Lin-CD34+CD38+IL-3Ra-CD45RA-)  Could be something like : Lin-, CD34+, CD38+, IL3RA-, CD45RA-. Separating the markers with commas and eliminating from the name IL-3 the (-) symbol to avoid confusion with the negative symbol. Daniel says that replacing the negative and positive symbols for "neg" and "pos" is another alternative if ambiguities persist.

Thank you very much

Juliana

**Comment by GFrosi** [comment]
Thanks a lot Juliana and Daniel,

I will perform the updates.

Cheers

Gabriella Frosi

**Comment by GFrosi** [comment]
Another question @juearcilaga , 

In this example:

IHECRE00000008.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, **CD63**
IHECRE00000016.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, **CD64**
IHECRE00000060.3 | primary cell culture | cord blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, **CD65**
IHECRE00000082.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, **CD66**
IHECRE00000084.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, **CD67**
IHECRE00000121.3 | primary cell culture | cord blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, **CD68**
IHECRE00000151.3 | primary cell culture | cord blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, **CD69**
IHECRE00000177.3 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, **CD70**
IHECRE00001398.1 | primary cell culture | venous blood | macrophage | CCR7, CD25, CD14, CD40,CD206, CD36, **CD71**

The last marker is always incremented by one (CD63, CD64, CD65...CD71). Is it correct? The same pattern occurred with the EpiRR associated with "inflammatory macrophage". Could you just confirm it?

Best

**Comment by juearcilaga** [comment]
Hi @GFrosi,

You are totally right, that is a mistake I made.  Should be CCR7+, CD25+, CD14+, CD40+ ,CD206+, CD36+, CD45+ in all. https://www.blueprint-epigenome.eu/UserFiles/File/Protocols/UCAM_BluePrint_Macrophage.pdf (Antibodies for Macrophage purity check)

Thank you very much

**Comment by GFrosi** [comment]
Thanks for your reply @juearcilaga!
