### ISSUE TITLE
EpiRR entries missing from Metadata table

### ISSUE THREAD

**Issue by SchulzLab** [IHEC/epimap-metadata-harmonization#34]
While looking at cell names, there were the following epic entries missing:
	
IHECRE00003524.1
IHECRE00003525.1

 IHECRE00003760.1
IHECRE00003799.1

There is one that was found IHECRE00003649.2, which appears to be from the same donor. It is unclear what the status of these entries is.

A similar issue with a different donor that has many entries for example with IHECRE00003526.1

**Comment by mlist** [comment]
Will check with Martin Hirst if those ids have processed data.

**Comment by quirinmanz** [comment]
We have a confirmation that we there is no staged or processed data for these four EpiRRs. The IDs have been removed from from the metadata table.
