### ISSUE TITLE
alpha_cell and beta_cell are inconsistent and have no cell ontology label

### ISSUE THREAD

**Issue by SchulzLab** [IHEC/epimap-metadata-harmonization#38]
There is an entry named beta_cell  (IHECRE00001868.2) does not have a cell ontology name, can this be renamed to "type B pancreatic cell" for which a cell ontology numbest exists (CL:0000169)?
  
There is an entry named alpha_cell (IHECRE00003717.1)  does not have a cell ontology name, can this be renamed to "pancreatic A cell" for which a cell ontology numbest exists (CL:0000171)?

**Comment by quirinmanz** [comment]
added the proposed ontology and renamed the cell_type
