### ISSUE TITLE
Health status column - Resolve the conflicting and redundant information on the health status column?

### ISSUE THREAD

**Issue by GFrosi** [IHEC/epimap-metadata-harmonization#39]
We have some conflicting combined information like "Cancer::normal" and "none::unknown", but also redundant info like "Adenocarcinoma ampulla of vater::cancer"; "Fatty Liver Disease::intrahepatic Metastasis"

**Comment by mlist** [comment]
We fixed most of those issues. For some entries in DEEP and KNIH we could not find a solution.

**Comment by quirinmanz** [comment]
Most of these should also be resolved by #70

**Comment by quirinmanz** [comment]
There are no more cases like this
