### ISSUE TITLE
Markers column: realocation of markers's information to other columns

### ISSUE THREAD

**Issue by GFrosi** [IHEC/epimap-metadata-harmonization#4]
The “marker” content for IHECRE00001436, IHECRE00001469 and IHECRE00000253 should probably be erased but the information perhaps relocated in a different column (“MLL-AF9 positive 62% blasts high BRE” and “MLL-AF9 positive 96% blasts normal BRE”, “early T cell precursor (ETP) phenotype”)

**Comment by daniel-rico** [comment]
IHECRE00001436.1
IHECRE00001469.1
Radboudumc, Nijmegen, Netherlands <- We actually don't know what markers they used.
MLL-AF9: aberrant fusion of MLL and AF9 genes. This actually a marker, so we would keep it there, but we would also add this to the phenotype.
62% blasts... this is probably the same thing than "gate" in the Italian samples. Probably part of phenotype too?
Stephan will write to Joost Martens.

IHECRE00000253.2
Necker's hospital <- See previous issue, Daniel will contact Salvatore Spicuglia to ask what markers were actually used.

**Comment by SchulzLab** [comment]
@daniel-rico any update on the issue mentioned above?

**Comment by mlist** [comment]
We decided to leave this as they are. AML samples have all additional information on the % of blasts.
