### ISSUE TITLE
Check the cell_type information with the ontology description term

### ISSUE THREAD

**Issue by GFrosi** [IHEC/epimap-metadata-harmonization#42]
Should we (programmatically) check (and perhaps uniformize in some cases) if the cell_type information matches with the ontology description term?

**Comment by mlist** [comment]
We decided that we need a script for this to identify the problematic fields which need to be resolved by hand.

**Comment by quirinmanz** [comment]
f7eab35d79b9101e1ae1991c260b8737a9681785
