### ISSUE TITLE
Rheumatic Disease has no NCIm Term 

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#46]
Rheumatic Disease (doid:1575) has no NCIm mapping. 

EpiRR Ids: IHECRE00003806.1 and IHECRE00003816.1

**Comment by asalhab** [comment]
after communication with Julia Polansky she suggested using Arthritis (CUI C4014799)

**Comment by asalhab** [comment]
Then I think we can use it
