### ISSUE TITLE
Differences between versions due to EpiRR update

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#47]
Due to new version in EpiRR, some additional changes have to be incorporated. 
The JSON shows the diff between the current metadata table, based on the old EpiRR version, (self) vs. the new metadata table, based on the new EpiRR version, (other). If only one of the two - 'self' or 'other' - is present, this column was NaN in the table it was compared to.

[diff_v0.5.txt](https://github.com/IHEC/epimap-metadata-harmonization/files/8041668/diff_v0.5.txt)

Additionally, there are 56 new entries that have to be checked:

[new_entries.txt](https://github.com/IHEC/epimap-metadata-harmonization/files/8041682/new_entries.txt)

**Comment by mlist** [comment]
@quirinmanz resolved most of the issues introduced by the changed EpiRRs.

**Comment by mlist** [comment]
New ROADMAP samples to be discussed with Misha Bilenky. It's not clear if they are actually being processed. If not, they can be excluded.

**Comment by mlist** [comment]
For EpiHK we should ask someone from EpiHK or Martin Hirst if these are included

**Comment by quirinmanz** [comment]
This might be a problem, if EpiRR has another update. We solved everything for this specific one
