### ISSUE TITLE
missing EFO ontologies for "trophoblast stem cell" IHECRE00004596.1 IHECRE00004597.1 IHECRE00004598.1 IHECRE00004599.1 IHECRE00004600.1 IHECRE00004601.1 IHECRE00004720 IHECRE00004721 IHECRE00004722

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#49]
no EFO ontology available for cell lines DG-75, bTS11 and CT27

**Comment by mlist** [comment]
We found one for DG-75: EFO:0002160

**Comment by quirinmanz** [comment]
As of now, for `sample_ontology_term_high_order_manual` we used 'stem cell derived cell line'

**Comment by quirinmanz** [comment]
IHECRE00004596.1 with bTS11 was changed to  "EVT-like cells were derived from trophoblast stem cells", but that is not in EFO as well

**Comment by quirinmanz** [comment]
IHECRE00004601.1 with bTS11 was changed to "Extravillous cytotrophoblast-like cells were induced from human trophoblast stem cells", but that is not in EFO as well

**Comment by quirinmanz** [comment]
IHECRE00004599 with CT27 was changed to "Syncytiotrophoblast-like cells were induced from human trophoblast stem cells", but that is not in EFO as well

**Comment by quirinmanz** [comment]
IHECRE00004720|IHECRE00004721|IHECRE00004722 were changed to "trophoblast stem cell" which is not in EFO

**Comment by quirinmanz** [comment]
IHECRE00004597 with bTS11 was changed to "Trophoblast stem cells were derived from a human blastocyst", but that is not in EFO as well

**Comment by quirinmanz** [comment]
IHECRE00004600 with CT27 was changed to "Trophoblast stem cells were derived from human cytotrophoblast cells", but that is not in EFO as well

**Comment by quirinmanz** [comment]
Using [stem cell derived cell line](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002886)
