### ISSUE TITLE
Markers column: rename information by exclusion of details of percentages

### ISSUE THREAD

**Issue by GFrosi** [IHEC/epimap-metadata-harmonization#5]
The “marker” content for IHECRE00000311 and IHECRE00000343 should probably  be renamed but not sure (“92% of the blasts shows: CD45_dim CD33++ CD64+ CD56+ CD34- CD14- and the 7% of CD45_dim CD33++ CD64+ CD56+ CD34- CD14+”). We performed few improvements according to the last IHEC meeting.

**Comment by daniel-rico** [comment]
This looks like there is a main population and some minor population(s) in the same sample. Stephan will ask Lucia Altucci.

**Comment by mlist** [comment]
Decided to leave it like it is.
