### ISSUE TITLE
CL for "breast variant human mammary epithelial cell"

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#51]
Use CL for [mammary gland epithelial cell](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002327)?

**Comment by mlist** [comment]
See #50

**Comment by quirinmanz** [comment]
Variant human mammary epithelial cells​ (vHMEC) were obtained de novo from cultured mammary (epithelial) cells,  which are spontaneously transformed. They are not normal cells. See https://doi.org/10.1038/35054579
