### ISSUE TITLE
uberon for "placenta (villi) tissue" IHECRE00004883.1 IHECRE00004897.1 IHECRE00004900.1

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#52]
Use [chorionic villus](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0007106)?

**Comment by mlist** [comment]
See #50

**Comment by quirinmanz** [comment]
As of now, we use [placenta, UBERON:0001987](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001987).
