### ISSUE TITLE
Markers column: how to proceed with 'gate' information in marker description

### ISSUE THREAD

**Issue by GFrosi** [IHEC/epimap-metadata-harmonization#6]
In the “marker” column, do we want (and how) to keep the “gate” information for IHECRE00001515 and IHECRE00000252 (“popolazione patologica (gate 89% circa) CD34+ HLA-DR+ CD19+”, “pathological population (gate 35%) with immunophenotype CD34- CD33+ CD13+ CD14+ CD64+ CD117-”) as well as 7 EpiRR from Blueprint (ex IHECRE00001243 “90% CD34- CD13+ CD33+ CD117+ CD9+ CD71+ HLA_DR- MPOcy-”). We performed few improvements according to the last IHEC meeting.

**Comment by daniel-rico** [comment]
We don't know what that gate % means. Stephan will contact Lucia Altucci to ask.

**Comment by daniel-rico** [comment]
Gate % corresponds to the amount of the leukemic cells phenotypically controlled.
Lucia provided some additional clinical info in an excel file, but not sure where to put this.

**Comment by mlist** [comment]
We decided to keep the gate % but to change some parts to English.
