### ISSUE TITLE
ontology for normal human stomach foveolar epithelial cells (surface mucous cells)

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#60]
Entries 
IHECRE00003661.1 ,IHECRE00003662.1 ,IHECRE00003663.1 ,IHECRE00003664.1 ,IHECRE00003665.1 ,IHECRE00003666.1 ,IHECRE00003667.1 ,IHECRE00003668.1 ,IHECRE00003669.1 ,IHECRE00003670.1 ,IHECRE00003671.1 ,IHECRE00003672.1 ,IHECRE00003673.1 ,IHECRE00003674.1
have cell_type `normal human stomach foveolar epithelial cells (surface mucous cells)` but ontology is available for [foveolar cell of stomach CL:0002179](http://purl.obolibrary.org/obo/CL_0002179) and [mucous cell of stomach CL:0002180](http://purl.obolibrary.org/obo/CL_0002180).

**Comment by mlist** [comment]
Should be CL:0002179
