### ISSUE TITLE
stromal cells with ontology fibroblast of mammary gland

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#61]
Entries 
IHECRE00004728.1 ,IHECRE00004731.1 ,IHECRE00004734.1
have cell_type `stromal cell` and ontology `fibroblast of mammary gland`

**Comment by mlist** [comment]
Markus e-mails Martin Hirst to ask about this. A cell can not be both fibroblast and stromal cell.

**Comment by quirinmanz** [comment]
> Stromal cells refer to a collection of cell types that are mesenchymal in origin and occur throughout the body.  The human breast is composed of stromal cells, adipocytes, endothelial cells and others and the mammary gland, itself composed of the 3 cell types  we have also profiled (BC, LP, LCs).
The stroma of the breast is primarily fibroblast cells, and indeed in the sorting we specifically deplete endothelial and adipocytes cells - so even more so here.
Thus, although the ontology language is a bit loose, (stroma is technically not part of the gland, but is part of the breast where the gland is embedded) - the ontology label is the most descriptive and should stay as is IMO.
