### ISSUE TITLE
Wrong biomaterial_type for KNIH entries

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#62]
Entries
IHECRE00001862.2 ,IHECRE00001863.2 ,IHECRE00001865.2 ,IHECRE00001870.2 ,IHECRE00001871.2
seem to have the wrong biomaterial type. Overview:
|EpiRR           |biomaterial_type|cell_type |sample_ontology_uri                          |
|----------------|----------------|----------|---------------------------------------------|
|IHECRE00001862.2|Primary Cell    |Islet_cell|http://purl.obolibrary.org/obo/UBERON_0000006|
|IHECRE00001863.2|Primary Cell    |Islet_cell|http://purl.obolibrary.org/obo/UBERON_0000006|
|IHECRE00001865.2|Primary Cell    |Islet_cell|http://purl.obolibrary.org/obo/UBERON_0000006|
|IHECRE00001870.2|Primary Cell    |Islet_cell|http://purl.obolibrary.org/obo/UBERON_0000006|
|IHECRE00001871.2|Primary Cell    |Islet_cell|http://purl.obolibrary.org/obo/UBERON_0000006|

**Comment by mlist** [comment]
Switch to http://purl.obolibrary.org/obo/CL_0008024 pancreas endocrine cells which includes the different types of cell associated with the islet cells, e.g. alpha, beta etc.
