### ISSUE TITLE
missing information for some AMED-CREST entries

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#63]
Three entries do not have corresponding terms in the cell ontology:
|EpiRR         |Description    |origin_sample|
|--------------|---------------|-------------|
|IHECRE00001959|Epithelial cells were isolated from a secretory phase endometrium.|placenta     |
|IHECRE00001961|Epithelial cells were isolated from a follicula phase endometrium.|             |
|IHECRE00003715|Epithelial cells were isolated from a secretory phase endometrium.|placenta     |

[epithelial cell CL:0000066](http://purl.obolibrary.org/obo/CL_0000066) may not be specific enough

**Comment by mlist** [comment]
Let's switch to biomaterial_type tissue and UBERON:0004811 (endometrium epithelial cells)

**Comment by mlist** [comment]
Remove placenta from origin sample since the cells do not originate from there.

**Comment by quirinmanz** [comment]
The biomaterial_type of these entries are reversed to primary cell and the sample_ontology_curie and cell_type is CL:0009084 and "epithelial cell of endometrial gland"
