### ISSUE TITLE
Missing CL for "ipsc" and "early neuron" for Entries IHECRE00003724.1, IHECRE00003727.1, IHECRE00003726.1, IHECRE00003729.1

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#64]
Currently, these entries are marked as "primary cell", but the cell_type is "ipsc". Are these supposed to be cell lines?

**Comment by mlist** [comment]
IPSC are induced pluripotent stem cells, so I'm also not sure if they would still count as primary cells...

**Comment by quirinmanz** [comment]
Entries IHECRE00003726.1 and IHECRE00003729.1 also have biomaterial_type "primary cell" but EFO ontology [iPSC derived cell line EFO:0005740](http://www.ebi.ac.uk/efo/EFO_0005740) and cell_type "early neuron", which is not in CL

**Comment by great0wizard** [comment]
I 'm a member of Korea Epigenome Project, We will check iPSC related entries (IHECRE00003724.1, IHECRE00003725.1, IHECRE00003726.1, IHECRE00003727.1, IHECRE00003728.1, IHECRE00003729.1) and  fix these for the issue

**Comment by mlist** [comment]
Thanks a lot! Are you planning to submit your fixes directly to EpiRR or will you report them here?

**Comment by great0wizard** [comment]
We will fix these issues in our metadata of EGA and then send  .refepi.json  to EpiRR for entries of the issue.

**Comment by quirinmanz** [comment]
@great0wizard did you make any progress on this? If you would like to keep the biomaterial_type as “primary cell”, we need ontology terms and curies for both "ipsc" and "early neuron" from [CL](https://www.ebi.ac.uk/ols/ontologies/cl).

**Comment by great0wizard** [comment]
I'm sorry for the delayed progress due to a lack of manpower.
I will fix our iPSC-related entries in two weeks as cell line & primary cell culture of sample metadata.

**Comment by quirinmanz** [comment]
You can also post your edits here or send it to me via email and I will fix it in the next metadata version

**Comment by great0wizard** [comment]
I 'm sorry. I had a car accident two days ago. 
I don't forget to fixing our entries. 
But I think that the fix will be done at end of the this month.

**Comment by mlist** [comment]
> I 'm sorry. I had a car accident two days ago. I don't forget to fixing our entries. But I think that the fix will be done at end of the this month.

I'm really sorry to hear that! Hope you're getting better soon!

**Comment by quirinmanz** [comment]
@great0wizard I hope you are doing well and recovered from your accident.
Did you have a chance to look at this? I can make the changes, I just need confirmation to change the _biomaterial_type_ to cell line. 
If they should stay **primary cell**s, could you check whether there is a corresponding CL term that fits better?

**Comment by quirinmanz** [comment]
Assignments for `harmonized_sample_ontology_intermediate`:
assigned "neural cell" for  "early neuron"
assigned "iPSC derived cell line" for "ipsc"

**Comment by quirinmanz** [comment]
It seems like the 6 entries IHECRE00003724 IHECRE00003725 IHECRE00003727 IHECRE00003726 IHECRE00003728 IHECRE00003729 are all somehow iPSC related. 
Their biomaterial_type will be changed from primary cell to cell line and as cell line ontology [iPSC derived cell line EFO:0005740](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005740) will be used.
This EFO is already that for 4 of the 6, and the other two have iPSC in their cell_type.
 As indicated in this comment https://github.com/IHEC/epimap-metadata-harmonization/issues/64#issuecomment-1262098363 they planned to change the biomaterial type.
