### ISSUE TITLE
NCIM Term for cell line "PC-3" IHECRE00003709

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#73]
Use [Stage IV Prostate Adenocarcinoma AJCC v7](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0862643)?

**Comment by KAndreeva** [comment]
Disease: Adenocarcinoma; Grade IV
NCIM term for Adenocarcinoma is CUI C2750272.
