### ISSUE TITLE
NCIM Term for cell line "NCI-H929" for IHECRE00004639

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#74]
[ATCC](https://www.atcc.org/products/crl-9068#:~:text=NCI%2DH929%20%5BH929%5D%20cells,lymphoblast%20Tissue%20Bone%3B%20Marrow%20Disease) has [Plasmacytoma C0032131](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0032131) as disease

IgA, kappa myeloma not in NCIM

**Comment by quirinmanz** [comment]
there is also [IgA myeloma C0563305](https://ncim.nci.nih.gov/ncimbrowser/pages/concept_details.jsf?dictionary=NCI%20Metathesaurus&code=C0563305&type=properties)

**Comment by quirinmanz** [comment]
related: 
MM.1S (IHECRE00003705) has "Immunoglobulin A Lambda Myeloma" in [ATCC](https://www.atcc.org/products/crl-2974)

**Comment by KAndreeva** [comment]
The disease for NCI-H929n cell line is Plasmacytoma.
The NCIM term for Plasmacytoma is CUI C0032131.
