### ISSUE TITLE
NCIM term for cell line "SUDHL6" for IHECRE00004673

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#75]
entry has disease "Large Cell Lymphoma; Diffuse Mixed Histiocytic And Lymphocytic Lymphoma; Follicular B Cell Lymphoma"
found the terms [Mixed Cell Lymphoma](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0024304), [Diffuse Large B-Cell Lymphoma](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0079744), [Follicular B-cell non-Hodgkin's lymphoma](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C1868944)

[ATCC](https://www.atcc.org/products/crl-2959) only links to Large Cell Lymphoma

**Comment by KAndreeva** [comment]
The disease for the SUDHL6  is Large Cell Lymphoma. There are so many NCIM terms for this disease and I am not sure what the appropriate one is?

**Comment by quirinmanz** [comment]
[Cellosaurus](https://www.cellosaurus.org/CVCL_2206) links to [NCIT](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C36080) with NCIM equivalent [Diffuse Large B-Cell Lymphoma Germinal Center B-Cell Type](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20MetaThesaurus&code=C1333295)
