### ISSUE TITLE
Markers column: move information to cell_type column (To Marcel Schulz)

### ISSUE THREAD

**Issue by GFrosi** [IHEC/epimap-metadata-harmonization#9]
The “marker” content for IHECRE00000253 could be moved to “cell_type” (“early T cell precursor (ETP) phenotype”).

**Comment by SchulzLab** [comment]
Interesting observation. I am not sure though currently. When I look at the other entries from this record it states: that it is from capillary blood (tissue_type) and a primary tissue from a t-cell acute lymphocytic leukaemia (donor_health_status). So I guess the question is whether the marker "early T cell precursor (ETP) phenotype" refers to something they observe looking at the results from sequencing all cells, or whether some kind of cell sorting was done. If something was sorted, we need to contact the people involved to know in detail which markers were used. Then it may be possible to derive a more  concrete cell type.

**Comment by daniel-rico** [comment]
EpiRR:
T-cell Acute Lymphocytic Leukemia from capillary blood of donor: Necker_TALL_001
--
I will contact Salvatore Spicuglia to ask about what markers did they use at Necker hospital (sample provider).

**Comment by mlist** [comment]
@daniel-rico were you able to follow up on this? we are still missing the appropriate markers.
